version: '3'

services:
  bmlt:
    build:
      context: .
      dockerfile: Dockerfile-bmltdebug
    ports:
      - "8000:80"
    env_file:
      - bmlt.env
    depends_on:
      - db
    volumes:
      - ../main_server:/var/www/html/main_server
  db:
    image: public.ecr.aws/m3g5z4b2/bmlt-root-server-sample-db:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bmlt_root_password
      MYSQL_DATABASE: bmlt
      MYSQL_USER: bmlt_user
      MYSQL_PASSWORD: bmlt_password
